ALTER TABLE skus ADD COLUMN IF NOT EXISTS name VARCHAR(255) COMMENT 'SKU名称';
ALTER TABLE skus ADD COLUMN IF NOT EXISTS description VARCHAR(500) COMMENT 'SKU描述';
ALTER TABLE skus ADD COLUMN IF NOT EXISTS properties VARCHAR(500) COMMENT 'SKU属性(JSON)';
ALTER TABLE skus ADD COLUMN IF NOT EXISTS price DECIMAL(10,2) COMMENT '售价';
ALTER TABLE skus ADD COLUMN IF NOT EXISTS original_price DECIMAL(10,2) COMMENT '原价';
